In [40]:
import pandas as pd
import os
from unidecode import unidecode
import sqlite3
from datetime import datetime

In [41]:
conn = sqlite3.connect(r'C:\Users\Pichau\OneDrive\Documentos\Estudos Dudu\7. atraso-voos\data\database.db')

In [42]:
df = pd.read_sql_query("SELECT * FROM brz_clima", conn)

In [43]:
df['anoRef'] = df['anoRef'].astype(int)
df['data'] = pd.to_datetime(df['data'], errors='coerce')
df['mesRef'] = df['data'].dt.month
df = df.replace('nan', pd.NA)

df = df[df['anoRef'] >= 2021]

In [44]:
df.isna().sum()

data                                        0
hora                                        0
precipitacaoTotal                          22
pressaoAtmosferica                         22
pressaoAtmosfericaMaxUltimaHora            27
pressaoAtmosfericaMinUltimaHora            28
radiacaoGlobal                          21027
temperaturaBulboSeco                       23
temperaturaPontoOrvalho                    23
temperaturaMaxUltimaHora                   27
temperaturaMinUltimaHora                   27
temperaturaPontoOrvalhoMaxUltimaHora       27
temperaturaPontoOrvalhoMinUltimaHora       28
umidadeRelativaMaxUltimaHora               27
umidadeRelativaMinUltimaHora               27
umidadeRelativa                            22
ventoDirecaoGraus                          23
ventoRajadaMax                             28
ventoVelocidade                            24
anoRef                                      0
mesRef                                      0
dtype: int64

In [45]:
df.isna().all(axis=1).sum()

np.int64(0)

In [46]:
df.iloc[:,2:-2].isna().all(axis=1).sum()

np.int64(22)

In [5]:
for ano in range(2021, 2026+1):
    print(f"Ano: {ano} | Quantidade de Datas Únicas: {len(df[df['anoRef'] == ano]['data'].unique())}")

Ano: 2021 | Quantidade de Datas Únicas: 365
Ano: 2022 | Quantidade de Datas Únicas: 365
Ano: 2023 | Quantidade de Datas Únicas: 365
Ano: 2024 | Quantidade de Datas Únicas: 366
Ano: 2025 | Quantidade de Datas Únicas: 365
Ano: 2026 | Quantidade de Datas Únicas: 90


In [6]:
for ano in range(2021, 2026+1):
    for mes in range(1, 12+1):
        print(f"Ano: {ano}")
        print(f"Mês: {mes} | Quantidade de Datas Únicas: {len(df[(df['anoRef'] == ano) & (df['mesRef'] == mes)]['data'].unique())}")

Ano: 2021
Mês: 1 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 2 | Quantidade de Datas Únicas: 28
Ano: 2021
Mês: 3 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 4 | Quantidade de Datas Únicas: 30
Ano: 2021
Mês: 5 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 6 | Quantidade de Datas Únicas: 30
Ano: 2021
Mês: 7 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 8 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 9 | Quantidade de Datas Únicas: 30
Ano: 2021
Mês: 10 | Quantidade de Datas Únicas: 31
Ano: 2021
Mês: 11 | Quantidade de Datas Únicas: 30
Ano: 2021
Mês: 12 | Quantidade de Datas Únicas: 31
Ano: 2022
Mês: 1 | Quantidade de Datas Únicas: 31
Ano: 2022
Mês: 2 | Quantidade de Datas Únicas: 28
Ano: 2022
Mês: 3 | Quantidade de Datas Únicas: 31
Ano: 2022
Mês: 4 | Quantidade de Datas Únicas: 30
Ano: 2022
Mês: 5 | Quantidade de Datas Únicas: 31
Ano: 2022
Mês: 6 | Quantidade de Datas Únicas: 30
Ano: 2022
Mês: 7 | Quantidade de Datas Únicas: 31
Ano: 2022
Mês: 8 | Quantidade de Datas Únicas: 

In [7]:
for col in df.columns:
    df = df[df['anoRef'] >= 2021]
    qtd_nulos = len(df[df[col].isna()])
    qtd_total = len(df)
    print(f"Column: {col} | Nulos: {qtd_nulos} | %Total: {(qtd_nulos/qtd_total)*100:.4f}%")
    print(df[df[col].isna()]['anoRef'].unique())
    print(df[df[col].isna()]['mesRef'].unique())
    print('----------------------------------')

Column: data | Nulos: 0 | %Total: 0.0000%
[]
[]
----------------------------------
Column: hora | Nulos: 0 | %Total: 0.0000%
[]
[]
----------------------------------
Column: precipitacaoTotal | Nulos: 22 | %Total: 0.0478%
[2022 2024 2025 2026]
[12 10  8  1]
----------------------------------
Column: pressaoAtmosferica | Nulos: 22 | %Total: 0.0478%
[2022 2024 2025 2026]
[12 10  8  1]
----------------------------------
Column: pressaoAtmosfericaMaxUltimaHora | Nulos: 27 | %Total: 0.0587%
[2022 2024 2025 2026]
[ 6 12  2 10  8  1]
----------------------------------
Column: pressaoAtmosfericaMinUltimaHora | Nulos: 28 | %Total: 0.0609%
[2022 2024 2025 2026]
[ 6 12  2 10  8  1]
----------------------------------
Column: radiacaoGlobal | Nulos: 21027 | %Total: 45.7268%
[2021 2022 2023 2024 2025 2026]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
----------------------------------
Column: temperaturaBulboSeco | Nulos: 23 | %Total: 0.0500%
[2022 2024 2025 2026]
[12  2 10  8  1]
-------------------------

In [58]:
df[~df['temperaturaPontoOrvalhoMinUltimaHora'].isna()].isna().sum()

data                                        0
hora                                        0
precipitacaoTotal                           0
pressaoAtmosferica                          0
pressaoAtmosfericaMaxUltimaHora             0
pressaoAtmosfericaMinUltimaHora             0
radiacaoGlobal                          21005
temperaturaBulboSeco                        0
temperaturaPontoOrvalho                     0
temperaturaMaxUltimaHora                    0
temperaturaMinUltimaHora                    0
temperaturaPontoOrvalhoMaxUltimaHora        0
temperaturaPontoOrvalhoMinUltimaHora        0
umidadeRelativaMaxUltimaHora                0
umidadeRelativaMinUltimaHora                0
umidadeRelativa                             0
ventoDirecaoGraus                           0
ventoRajadaMax                              1
ventoVelocidade                             0
anoRef                                      0
mesRef                                      0
dtype: int64

In [9]:
#from itables import show
from itables import init_notebook_mode
#init_notebook_mode(all_interactive=True)

df_2022 = df[df['anoRef'] == 2022]

df_2022[df_2022['umidadeRelativa'] == 'nan']

,data,hora,precipitacaoTotal,pressaoAtmosferica,pressaoAtmosfericaMaxUltimaHora,pressaoAtmosfericaMinUltimaHora,radiacaoGlobal,temperaturaBulboSeco,temperaturaPontoOrvalho,temperaturaMaxUltimaHora,...,temperaturaPontoOrvalhoMaxUltimaHora,temperaturaPontoOrvalhoMinUltimaHora,umidadeRelativaMaxUltimaHora,umidadeRelativaMinUltimaHora,umidadeRelativa,ventoDirecaoGraus,ventoRajadaMax,ventoVelocidade,anoRef,mesRef
